# This configuration creates two custom
# test pipelines each running a different python version.

pipelines:
  custom:
    test-py2:
      - step:
          image: python:2.7
          script:
            - pip install numpy
            - python setup.py test
    test-py3:
      - step:
          image: python:3.5
          script:
            - pip install numpy
            - python setup.py test
